language: ruby
sudo: false

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version

install: bundle install --without development doc

script: bundle exec rake

env: JRUBY_OPTS="$JRUBY_OPTS --debug"

rvm:
  # Include JRuby first because it takes the longest
  - jruby-9.1.16.0
  - 2.3
  - 2.4
  - 2.5

matrix:
  fast_finish: true
  include:
  # Only run RuboCop and Yardstick metrics on the latest Ruby
  - rvm: 2.5
    env: SUITE="rubocop"
  - rvm: 2.5
    env: SUITE="yardstick"

branches:
  only:
    - master
